apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        backend: backend
    spec:
      containers:
        - name: backend
          image: registry.cn-shenzhen.aliyuncs.com/pipipan/backend:master
          imagePullPolicy: Always
          resources:
          # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  selector:
    backend: backend
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31001
