apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        backend: application
    spec:
      containers:
        - name: application
          image: registry.cn-shenzhen.aliyuncs.com/pipipan/meetingroom:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: application
spec:
  selector:
    backend: application
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000

